#!/bin/bash
# Script للعميل: مسح الـ cache وإعادة تحميل الصفحة

echo "=================================="
echo "   تعليمات للعميل - مسح الـ Cache"
echo "=================================="
echo ""
echo "يرجى اتباع الخطوات التالية لرؤية التغييرات:"
echo ""
echo "📱 على الموبايل (Android/iPhone):"
echo "   1️⃣  افتح المتصفح (Chrome/Safari)"
echo "   2️⃣  اضغط على القائمة (⋮ أو ...)"
echo "   3️⃣  اختر 'الإعدادات' أو 'Settings'"
echo "   4️⃣  اختر 'الخصوصية' أو 'Privacy'"
echo "   5️⃣  اضغط 'مسح بيانات التصفح' أو 'Clear browsing data'"
echo "   6️⃣  اختر 'الصور والملفات المخزنة مؤقتاً'"
echo "   7️⃣  اضغط 'مسح البيانات'"
echo "   8️⃣  ارجع للموقع وحدّث الصفحة"
echo ""
echo "💻 على الكمبيوتر:"
echo "   🔵 Chrome/Edge:"
echo "      اضغط: Ctrl + Shift + Delete (Windows)"
echo "      أو: Cmd + Shift + Delete (Mac)"
echo "      اختر 'Cached images and files' واضغط Clear"
echo ""
echo "   🔴 Firefox:"
echo "      اضغط: Ctrl + Shift + Delete"
echo "      اختر 'Cache' واضغط Clear Now"
echo ""
echo "   🟢 Safari:"
echo "      اضغط: Cmd + Option + E"
echo "      أو: Safari > Clear History"
echo ""
echo "=================================="
echo "   طريقة أسرع: Hard Refresh"
echo "=================================="
echo ""
echo "💻 على الكمبيوتر:"
echo "   • Windows: Ctrl + Shift + R"
echo "   • Mac: Cmd + Shift + R"
echo ""
echo "📱 على الموبايل:"
echo "   1. اضغط على أيقونة التحديث مطولاً"
echo "   2. اختر 'Hard Refresh' إن ظهرت"
echo "   3. أو امسح الـ cache كما في الخطوات أعلاه"
echo ""
echo "=================================="
echo "   اختبار التغييرات"
echo "=================================="
echo ""
echo "بعد مسح الـ Cache، افتح:"
echo ""
echo "1️⃣  صفحة المدرسين:"
echo "    https://sys.educore.software/teachers/"
echo "    ✅ يجب أن تشوف عمود 'المواد الدراسية'"
echo ""
echo "2️⃣  صفحة المدفوعات:"
echo "    https://sys.educore.software/payments/"
echo "    ✅ يجب أن تشوف عمود 'المدرس' و 'حالة المدرس'"
echo ""
echo "3️⃣  تعديل طالب:"
echo "    https://sys.educore.software/students/"
echo "    ✅ افتح أي طالب للتعديل"
echo "    ✅ الأرقام بدون +20"
echo ""
echo "=================================="
echo ""
echo "⚠️  ملاحظة مهمة:"
echo "   إذا لم تظهر التغييرات بعد مسح الـ Cache:"
echo "   • تأكد من تسجيل الدخول"
echo "   • جرّب متصفح آخر"
echo "   • جرّب من وضع التصفح الخفي (Incognito/Private)"
echo ""
echo "=================================="
