# Generated by Django 5.1.4 on 2026-01-24 05:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_code', models.CharField(db_index=True, help_text='كود قصير ومميز (مثال: 1001، 5050)', max_length=10, unique=True, verbose_name='كود الطالب')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('parent_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بالصيغة: '+999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='هاتف ولي الأمر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'db_table': 'students',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_status', models.CharField(choices=[('normal', 'عادي'), ('symbolic', 'مبلغ رمزي'), ('exempt', 'إعفاء كامل')], default='normal', max_length=10, verbose_name='الحالة المالية')),
                ('custom_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ المخصص')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.group', verbose_name='المجموعة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل طالب في مجموعة',
                'verbose_name_plural': 'تسجيلات الطلاب في المجموعات',
                'db_table': 'student_group_enrollments',
                'unique_together': {('student', 'group')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(related_name='enrolled_students', through='students.StudentGroupEnrollment', to='teachers.group', verbose_name='المجموعات'),
        ),
    ]
