# Generated by Django 5.2.10 on 2026-02-07 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education_stage',
            field=models.CharField(blank=True, choices=[('primary', 'ابتدائي'), ('preparatory', 'إعدادي'), ('secondary', 'ثانوي')], max_length=20, verbose_name='المرحلة الدراسية'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_type',
            field=models.CharField(choices=[('general', 'عام'), ('languages', 'لغات'), ('experimental', 'تجريبي')], default='general', max_length=20, verbose_name='نوع التعليم'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_year',
            field=models.CharField(blank=True, choices=[('1', 'أولى'), ('2', 'ثانية'), ('3', 'ثالثة')], max_length=5, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', help_text='لتحديد نوع المجموعة المناسبة', max_length=10, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بالصيغة: '+999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(help_text='للأولاد = الأب، للبنات = الأم/الأخت', max_length=17, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بالصيغة: '+999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='هاتف ولي الأمر'),
        ),
    ]
