# Generated by Django 5.0.1 on 2026-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_education_stage_student_education_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="last_payment_date",
            field=models.DateField(
                blank=True,
                help_text="تاريخ تفعيل آخر اشتراك",
                null=True,
                verbose_name="تاريخ آخر دفع",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="subscription_expiry_date",
            field=models.DateField(
                blank=True,
                help_text="تاريخ انتهاء صلاحية الاشتراك (30 يوم من التفعيل)",
                null=True,
                verbose_name="تاريخ انتهاء الاشتراك",
            ),
        ),
    ]
