# Generated by Django 5.2.10 on 2026-02-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_add_qr_code_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studentgroupenrollment",
            new_name="student_gro_is_new__88c21f_idx",
            old_name="stu_cred_idx",
        ),
        migrations.RenameIndex(
            model_name="studentgroupenrollment",
            new_name="student_gro_is_fina_aed4ea_idx",
            old_name="stu_fin_block_idx",
        ),
    ]
