# Generated by Django 5.0.1 on 2026-03-09 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_student_last_payment_date_and_more"),
        ("teachers", "0003_update_education_year_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgroupenrollment",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="teachers.group",
                verbose_name="المجموعة",
            ),
        ),
        migrations.AlterField(
            model_name="studentgroupenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_enrollments",
                to="students.student",
                verbose_name="الطالب",
            ),
        ),
    ]
