# Generated by Django 5.0.1 on 2026-03-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_studentgroupenrollment_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="education_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "الأول"),
                    ("2", "الثاني"),
                    ("3", "الثالث"),
                    ("4", "الرابع"),
                    ("5", "الخامس"),
                    ("6", "السادس"),
                ],
                max_length=5,
                verbose_name="السنة الدراسية",
            ),
        ),
    ]
