# Generated by Django 5.0.1 on 2026-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_add_soft_delete_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgroupenrollment",
            name="financial_status",
            field=models.CharField(
                choices=[
                    ("normal", "عادي"),
                    ("symbolic", "مبلغ رمزي"),
                    ("exempt", "إعفاء كامل"),
                    ("per_session", "دفع بالحصة"),
                ],
                default="normal",
                max_length=15,
                verbose_name="الحالة المالية",
            ),
        ),
    ]
