# Generated by Django 5.0.1 on 2026-04-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_alter_studentgroupenrollment_financial_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="grade",
        ),
    ]
