# Generated by Django 5.0.1 on 2026-04-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_remove_student_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroupenrollment",
            name="grace_until",
            field=models.DateField(
                blank=True,
                help_text="تاريخ انتهاء المهلة - يسمح للطالب بالدخول بدون دفع حتى هذا التاريخ",
                null=True,
                verbose_name="مهلة حتى تاريخ",
            ),
        ),
    ]
