# Generated by Django 5.0.1 on 2026-05-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_add_grace_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroupenrollment',
            name='cycle_end_date',
            field=models.DateField(blank=True, help_text='تاريخ الانتهاء المحسوب لدورة الفوترة الحالية', null=True, verbose_name='نهاية دورة الفوترة'),
        ),
        migrations.AddField(
            model_name='studentgroupenrollment',
            name='cycle_start_date',
            field=models.DateField(blank=True, help_text='تاريخ بدء دورة الفوترة الحالية (session-based billing cycle)', null=True, verbose_name='بداية دورة الفوترة'),
        ),
        migrations.AddField(
            model_name='studentgroupenrollment',
            name='sessions_per_cycle',
            field=models.PositiveIntegerField(default=0, help_text='عدد الحصص لكل دورة فوترة (0 = استخدام إعدادات المجموعة)', verbose_name='عدد الحصص في الدورة'),
        ),
    ]
