# Generated by Django 5.0.1 on 2026-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_per_session_financial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_payment_date',
            field=models.DateField(blank=True, editable=False, help_text='مهمل — لم يعد مستخدماً، انظر Payment.paid_on لكل مجموعة', null=True, verbose_name='تاريخ آخر دفع (مهمل)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subscription_expiry_date',
            field=models.DateField(blank=True, editable=False, help_text='مهمل — لم يعد مستخدماً، الاستحقاق الآن بالحصص لكل مجموعة', null=True, verbose_name='تاريخ انتهاء الاشتراك (مهمل)'),
        ),
    ]
