# Generated by Django 5.0.1 on 2026-08-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_deprecate_subscription_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='education_stage',
            field=models.CharField(blank=True, choices=[('primary', 'ابتدائي'), ('preparatory', 'إعدادي'), ('secondary', 'ثانوي'), ('foundation', 'تأسيس'), ('courses', 'كورسات')], max_length=20, verbose_name='المرحلة الدراسية'),
        ),
    ]
