# Generated by Django 5.0.1 on 2026-09-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0014_alter_student_education_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="subscription_plan",
            field=models.CharField(
                choices=[("regular", "عادي"), ("bundle_5", "باقة 5 مواد")],
                default="regular",
                help_text="باقة 5 مواد: للمرحلة الإعدادية — تظهر كشارة بجوار اسم الطالب في كل الشاشات",
                max_length=20,
                verbose_name="خطة الاشتراك",
            ),
        ),
    ]
