# Generated by Django 5.2.10 on 2026-01-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("month", models.DateField(verbose_name="الشهر")),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ المطلوب"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="المبلغ المدفوع",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الدفع"
                    ),
                ),
                (
                    "sessions_attended",
                    models.IntegerField(default=0, verbose_name="عدد الحصص"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "مدفوع"),
                            ("partial", "مدفوع جزئياً"),
                            ("unpaid", "غير مدفوع"),
                        ],
                        default="unpaid",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="teachers.group",
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-month"],
                "unique_together": {("student", "group", "month")},
            },
        ),
    ]
