# Generated by Django 5.0.1 on 2026-03-09 00:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("students", "0004_student_last_payment_date_and_more"),
        ("teachers", "0003_update_education_year_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount_due",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="المبلغ المطلوب",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="المبلغ المدفوع",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="teachers.group",
                verbose_name="المجموعة",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="month",
            field=models.DateField(db_index=True, verbose_name="الشهر"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="sessions_attended",
            field=models.PositiveIntegerField(default=0, verbose_name="عدد الحصص"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="students.student",
            ),
        ),
    ]
