# Generated by Django 5.0.1 on 2026-03-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0002_alter_payment_amount_due_alter_payment_amount_paid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="sessions_total",
            field=models.PositiveIntegerField(
                default=4, verbose_name="إجمالي الحصص في الشهر"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="sessions_attended",
            field=models.PositiveIntegerField(
                default=0, verbose_name="عدد الحصص المحضورة"
            ),
        ),
    ]
