# Generated by Django 5.2.10 on 2026-02-01 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_add_payment_audit_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymentauditlog",
            new_name="payment_aud_student_242867_idx",
            old_name="pay_audit_stu_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentauditlog",
            new_name="payment_aud_action_73608c_idx",
            old_name="pay_audit_act_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentauditlog",
            new_name="payment_aud_perform_1efa79_idx",
            old_name="pay_audit_usr_idx",
        ),
        migrations.AlterField(
            model_name="paymentauditlog",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_payment_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم بواسطة",
            ),
        ),
    ]
