# Generated by Django 5.0.1 on 2026-05-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_sessions_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_cycle_completed',
            field=models.BooleanField(default=False, help_text='هل اكتملت دورة الفوترة لهذا الشهر وبدأت دورة جديدة', verbose_name='اكتملت دورة الفوترة'),
        ),
    ]
