# Generated by Django 5.0.1 on 2026-07-24 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_billing_cycle_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_exempt',
            field=models.BooleanField(db_index=True, default=False, help_text='صف مُعفى (مصروفات = صفر). يُحسب كـ«مدفوع» لأغراض الحضور فقط ولا يدخل في نسبة التحصيل.', verbose_name='إعفاء كامل'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='موجب للتحصيل، سالب لعكس عملية سابقة', max_digits=10, verbose_name='المبلغ')),
                ('kind', models.CharField(choices=[('payment', 'دفعة'), ('reversal', 'عكس/استرداد'), ('opening', 'رصيد سابق'), ('adjustment', 'تسوية')], default='payment', max_length=12, verbose_name='نوع الحركة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'حركة دفع',
                'verbose_name_plural': 'حركات الدفع',
                'db_table': 'payment_transactions',
                'ordering': ['-created_at', '-transaction_id'],
                'indexes': [models.Index(fields=['payment', 'created_at'], name='paytxn_payment_created_idx')],
            },
        ),
    ]
