# Generated by Django 5.0.1 on 2026-08-27 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_cycle_billing_fields'),
        ('payments', '0006_backfill_payment_ledger'),
        ('students', '0012_remove_per_session_financial_status'),
        ('teachers', '0013_cycle_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text='مفتاح الفوترة الفعلي — ``month`` يبقى مشتقًا منه للتوافق مع التقارير القديمة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='teachers.groupcycle', verbose_name='دورة الفوترة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='entitlement_start_seq',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ترتيب أول حصة مستحقة في الدورة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='entitlement_start_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attendance.session', verbose_name='أول حصة مستحقة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_on',
            field=models.DateField(blank=True, help_text='التاريخ الفعلي الذي دفع فيه ولي الأمر (يُدخله الموظف يدويًا) — بخلاف payment_date المُشتق تلقائيًا من سجل الحركات المحاسبي', null=True, verbose_name='تاريخ الدفع'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='effective_on',
            field=models.DateField(blank=True, help_text='التاريخ الذي أعطاه ولي الأمر (قد يسبق created_at)، بخلاف created_at الذي يبقى ثابتًا ولا يُعدَّل أبدًا كدليل تدقيق', null=True, verbose_name='تاريخ الدفع الفعلي'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sessions_attended',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الحصص المستهلكة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sessions_total',
            field=models.PositiveIntegerField(default=4, verbose_name='عدد الحصص المستحقة'),
        ),
        migrations.CreateModel(
            name='PaymentPackage',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('cycles', models.PositiveSmallIntegerField(verbose_name='عدد الدورات')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي المدفوع')),
                ('list_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي بدون خصم')),
                ('paid_on', models.DateField(verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_packages_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_packages', to='teachers.group', verbose_name='المجموعة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_packages', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'باقة دفع',
                'verbose_name_plural': 'باقات الدفع',
                'db_table': 'payment_packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentpackage', verbose_name='الباقة'),
        ),
    ]
