# Generated by Django 5.0.1 on 2026-08-27 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_cycle_billing_fields'),
        ('payments', '0008_backfill_cycles'),
        ('students', '0012_remove_per_session_financial_status'),
        ('teachers', '0013_cycle_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('student', 'cycle'), name='uniq_payment_student_cycle'),
        ),
    ]
