# Generated by Django 5.0.1 on 2026-08-27 11:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_cycle_unique_constraint'),
        ('students', '0013_deprecate_subscription_fields'),
        ('teachers', '0013_cycle_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSettlement',
            fields=[
                ('settlement_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('period_label', models.CharField(blank=True, max_length=64, verbose_name='تسمية الفترة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد')], db_index=True, default='draft', max_length=10, verbose_name='الحالة')),
                ('computed_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي المحسوب')),
                ('adjusted_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي بعد التعديل')),
                ('center_share', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='نصيب المركز')),
                ('teacher_share', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='نصيب المدرس')),
                ('default_center_percentage', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='نسبة المركز الافتراضية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتُمد بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_reopened', to=settings.AUTH_USER_MODEL, verbose_name='أُعيد فتحه بواسطة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='teachers.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'كشف تصفية مدرس',
                'verbose_name_plural': 'كشوفات تصفية المدرسين',
                'db_table': 'teacher_settlements',
                'ordering': ['-period_start', 'teacher_id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSettlementLine',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('sessions_consumed', models.PositiveIntegerField(default=0, verbose_name='الحصص المستهلكة')),
                ('sessions_entitled', models.PositiveIntegerField(default=0, verbose_name='الحصص المستحقة')),
                ('session_dates', models.JSONField(blank=True, default=list, verbose_name='تواريخ الحصص')),
                ('fee_full', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الكامل للدورة')),
                ('computed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المحسوب آليًا')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المُحصَّل فعليًا')),
                ('financial_status', models.CharField(blank=True, max_length=15, verbose_name='الحالة المالية')),
                ('group_center_percentage', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='نسبة المركز للمجموعة')),
                ('is_excluded', models.BooleanField(default=False, verbose_name='مستبعد')),
                ('is_free', models.BooleanField(default=False, verbose_name='حالة مجانية/خاصة')),
                ('amount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ مُعدَّل')),
                ('percentage_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة مُعدَّلة')),
                ('override_reason', models.CharField(blank=True, max_length=255, verbose_name='سبب التعديل')),
                ('effective_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ الفعلي بعد التعديل')),
                ('line_center_share', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب المركز')),
                ('line_teacher_share', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب المدرس')),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_lines', to='teachers.groupcycle', verbose_name='الدورة')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_lines_edited', to=settings.AUTH_USER_MODEL, verbose_name='آخر مُعدِّل')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='teachers.group', verbose_name='المجموعة')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_lines', to='payments.payment', verbose_name='الدفعة (للتتبع فقط)')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.teachersettlement', verbose_name='الكشف')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سطر تصفية',
                'verbose_name_plural': 'سطور التصفية',
                'db_table': 'teacher_settlement_lines',
                'ordering': ['group__group_name', 'student__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='teachersettlement',
            index=models.Index(fields=['teacher', 'status'], name='settle_teacher_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersettlement',
            unique_together={('teacher', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='teachersettlementline',
            index=models.Index(fields=['settlement', 'group'], name='settleline_stl_grp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersettlementline',
            unique_together={('settlement', 'group', 'student')},
        ),
    ]
