# Generated by Django 5.2.10 on 2026-02-07 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_attendances', to=settings.AUTH_USER_MODEL, verbose_name='المشرف المسجل'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('student_create', 'إنشاء طالب'), ('student_update', 'تعديل طالب'), ('student_delete', 'حذف طالب'), ('attendance_scan', 'تسجيل حضور'), ('payment_create', 'إنشاء دفعة'), ('payment_update', 'تعديل دفعة'), ('group_create', 'إنشاء مجموعة'), ('group_update', 'تعديل مجموعة'), ('enrollment_create', 'تسجيل في مجموعة'), ('enrollment_remove', 'إزالة من مجموعة'), ('override_financial', 'تجاوز القيود المالية'), ('override_time', 'تجاوز قيود الوقت')], max_length=30, verbose_name='نوع العملية')),
                ('description', models.TextField(verbose_name='تفاصيل العملية')),
                ('target_model', models.CharField(blank=True, max_length=50, verbose_name='الموديل المستهدف')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='معرف السجل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجلات النشاط',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
