# Generated by Django 5.0.1 on 2026-03-09 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_supervisor_activitylog"),
        ("students", "0004_student_last_payment_date_and_more"),
        ("teachers", "0003_update_education_year_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendances",
                to="attendance.session",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendances",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="teachers.group",
            ),
        ),
    ]
