# Generated by Django 5.2.10 on 2026-02-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_add_strict_mode_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="attendance",
            new_name="attendances_status_22cc48_idx",
            old_name="attend_status_entry_idx",
        ),
        migrations.RenameIndex(
            model_name="attendance",
            new_name="attendances_scan_ti_822e92_idx",
            old_name="attend_scan_time_idx",
        ),
        migrations.RenameIndex(
            model_name="attendance",
            new_name="attendances_color_c_c1202c_idx",
            old_name="attend_color_idx",
        ),
        migrations.RenameIndex(
            model_name="blockedattempt",
            new_name="blocked_att_student_85da5b_idx",
            old_name="block_att_student_idx",
        ),
        migrations.RenameIndex(
            model_name="blockedattempt",
            new_name="blocked_att_reason_65fce5_idx",
            old_name="block_att_reason_idx",
        ),
        migrations.RenameIndex(
            model_name="blockedattempt",
            new_name="blocked_att_attempt_ef3848_idx",
            old_name="block_att_time_idx",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="color_code",
            field=models.CharField(
                choices=[
                    ("green", "green"),
                    ("red", "red"),
                    ("red", "red"),
                    ("white", "white"),
                    ("yellow", "yellow"),
                    ("gray", "gray"),
                ],
                default="white",
                help_text="لون عرض الحالة على شاشة الكشك",
                max_length=20,
                verbose_name="كود اللون",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="rejection_reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="سبب الرفض"
            ),
        ),
    ]
