# Generated by Django 4.2.27 on 2026-02-01 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_qr_code_base64_teacher_qr_code_generated_at'),
        ('attendance', '0003_rename_attend_status_entry_idx_attendances_status_22cc48_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskDevice',
            fields=[
                ('device_id', models.CharField(help_text='معرف فريد للجهاز (مثال: KIOSK-001)', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='معرف الجهاز')),
                ('device_name', models.CharField(help_text='اسم وصفي للجهاز (مثال: جهاز القاعة 1)', max_length=100, verbose_name='اسم الجهاز')),
                ('is_active', models.BooleanField(default=True, help_text='هل الجهاز يعمل حالياً؟', verbose_name='نشط')),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='آخر مرة أرسل فيها الجهاز إشارة حياة', null=True, verbose_name='آخر اتصال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(help_text='القاعة التي يخدمها هذا الجهاز', on_delete=django.db.models.deletion.PROTECT, related_name='kiosks', to='teachers.room', verbose_name='القاعة المرتبطة')),
            ],
            options={
                'verbose_name': 'جهاز مسح ضوئي',
                'verbose_name_plural': 'أجهزة المسح الضوئي',
                'db_table': 'kiosk_devices',
                'ordering': ['device_id'],
            },
        ),
    ]
