# Generated by Django 5.0.1 on 2026-03-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0003_alter_attendance_session_alter_attendance_student_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("student_create", "إنشاء طالب"),
                    ("student_update", "تعديل طالب"),
                    ("student_delete", "حذف طالب"),
                    ("student_toggle", "تغيير حالة طالب"),
                    ("attendance_scan", "تسجيل حضور"),
                    ("payment_create", "إنشاء دفعة"),
                    ("payment_update", "تعديل دفعة"),
                    ("payment_record", "تسجيل دفعة"),
                    ("teacher_create", "إضافة مدرس"),
                    ("teacher_update", "تعديل مدرس"),
                    ("teacher_delete", "حذف مدرس"),
                    ("group_create", "إنشاء مجموعة"),
                    ("group_update", "تعديل مجموعة"),
                    ("group_delete", "حذف مجموعة"),
                    ("room_create", "إضافة قاعة"),
                    ("room_update", "تعديل قاعة"),
                    ("room_delete", "حذف قاعة"),
                    ("subject_create", "إضافة مادة"),
                    ("subject_update", "تعديل مادة"),
                    ("subject_delete", "حذف مادة"),
                    ("user_create", "إنشاء مستخدم"),
                    ("user_update", "تعديل مستخدم"),
                    ("user_toggle", "تغيير حالة مستخدم"),
                    ("enrollment_create", "تسجيل في مجموعة"),
                    ("enrollment_remove", "إزالة من مجموعة"),
                    ("override_financial", "تجاوز القيود المالية"),
                    ("override_time", "تجاوز قيود الوقت"),
                ],
                max_length=30,
                verbose_name="نوع العملية",
            ),
        ),
    ]
