# Generated by Django 5.0.1 on 2026-05-25 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_activitylog_action'),
        ('students', '0011_studentgroupenrollment_cycle_end_date_and_more'),
        ('teachers', '0009_alter_subject_education_stage_alter_subject_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('student_create', 'إنشاء طالب'), ('student_update', 'تعديل طالب'), ('student_delete', 'حذف طالب'), ('student_toggle', 'تغيير حالة طالب'), ('attendance_scan', 'تسجيل حضور'), ('payment_create', 'إنشاء دفعة'), ('payment_update', 'تعديل دفعة'), ('payment_record', 'تسجيل دفعة'), ('teacher_create', 'إضافة مدرس'), ('teacher_update', 'تعديل مدرس'), ('teacher_delete', 'حذف مدرس'), ('group_create', 'إنشاء مجموعة'), ('group_update', 'تعديل مجموعة'), ('group_delete', 'حذف مجموعة'), ('room_create', 'إضافة قاعة'), ('room_update', 'تعديل قاعة'), ('room_delete', 'حذف قاعة'), ('subject_create', 'إضافة مادة'), ('subject_update', 'تعديل مادة'), ('subject_delete', 'حذف مادة'), ('user_create', 'إنشاء مستخدم'), ('user_update', 'تعديل مستخدم'), ('user_toggle', 'تغيير حالة مستخدم'), ('enrollment_create', 'تسجيل في مجموعة'), ('enrollment_remove', 'إزالة من مجموعة'), ('override_financial', 'تجاوز القيود المالية'), ('override_time', 'تجاوز قيود الوقت'), ('exception_grant', 'منح استثناء'), ('exception_revoke', 'إلغاء استثناء')], max_length=30, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخر'), ('absent', 'غائب'), ('exception', 'استثناء')], max_length=15),
        ),
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('exception_id', models.AutoField(primary_key=True, serialize=False)),
                ('exception_type', models.CharField(choices=[('payment', 'استثناء دفع — Payment Exception'), ('late_arrival', 'استثناء تأخير — Late Arrival Exception')], max_length=20, verbose_name='نوع الاستثناء')),
                ('reason_type', models.CharField(choices=[('forgot_money', 'نسي المصروفات – Forgot money'), ('another_class', 'كان في حصة أخرى – Was attending another class'), ('transportation', 'تأخر بسبب المواصلات – Delayed by transportation'), ('medical', 'ظروف صحية طارئة – Medical emergency'), ('family_emergency', 'ظرف عائلي طارئ – Family emergency'), ('system_error', 'خطأ في النظام – System error'), ('admin_override', 'تجاوز إداري – Administrative override'), ('other', 'سبب آخر – Other')], default='other', max_length=30, verbose_name='سبب الاستثناء')),
                ('custom_reason', models.TextField(blank=True, help_text="تفاصيل إضافية إن كان السبب 'آخر' أو لتوضيح أكثر", verbose_name='سبب مخصص')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exception_records', to='teachers.group', verbose_name='المجموعة')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_records', to='attendance.session', verbose_name='الحصة المرتبطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exception_records', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل استثناء',
                'verbose_name_plural': 'سجلات الاستثناءات',
                'db_table': 'exception_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='exception_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.exceptionrecord', verbose_name='سجل الاستثناء المرتبط'),
        ),
    ]
