# Generated by Django 5.0.1 on 2026-08-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_activitylog_action'),
        ('teachers', '0013_cycle_billing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='teachers.groupcycle', verbose_name='دورة الفوترة'),
        ),
        migrations.AddField(
            model_name='session',
            name='sequence_in_cycle',
            field=models.PositiveSmallIntegerField(blank=True, help_text='فارغ للحصص الملغاة — لا تُحتسب على أي طالب', null=True, verbose_name='ترتيب الحصة في الدورة'),
        ),
    ]
