# Generated by Django 5.0.1 on 2026-10-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_activitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.CharField(blank=True, default='', help_text='سبب العذر/الاستثناء اليدوي — بيظهر على الخانة وتحت جدول الحضور', max_length=255, verbose_name='ملاحظة الحصة'),
        ),
    ]
