# Generated by Django 5.1.4 on 2026-01-24 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القاعة')),
                ('capacity', models.PositiveIntegerField(verbose_name='السعة القصوى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قاعة',
                'verbose_name_plural': 'القاعات',
                'db_table': 'rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='اسم المدرس')),
                ('phone', models.CharField(max_length=17, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('specialization', models.CharField(max_length=100, verbose_name='التخصص')),
                ('hire_date', models.DateField(verbose_name='تاريخ التعيين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'المدرسين',
                'db_table': 'teachers',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100, verbose_name='اسم المجموعة')),
                ('schedule_day', models.CharField(choices=[('Saturday', 'السبت'), ('Sunday', 'الأحد'), ('Monday', 'الاثنين'), ('Tuesday', 'الثلاثاء'), ('Wednesday', 'الأربعاء'), ('Thursday', 'الخميس'), ('Friday', 'الجمعة')], max_length=10, verbose_name='يوم الحصة')),
                ('schedule_time', models.TimeField(verbose_name='وقت الحصة')),
                ('standard_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر القياسي')),
                ('center_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='نسبة السنتر %')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='teachers.room', verbose_name='القاعة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='teachers.teacher', verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'مجموعة',
                'verbose_name_plural': 'المجموعات',
                'db_table': 'groups',
                'constraints': [models.UniqueConstraint(fields=('room', 'schedule_day', 'schedule_time'), name='unique_room_schedule', violation_error_message='يوجد تعارض: القاعة محجوزة في نفس اليوم والوقت')],
            },
        ),
    ]
