# Generated by Django 5.2.10 on 2026-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المادة')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='group',
            name='unique_room_schedule',
        ),
        migrations.AddField(
            model_name='group',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=120, help_text='مدة الحصة بالدقائق (مثال: 120 = ساعتين)', verbose_name='مدة الحصة (بالدقائق)'),
        ),
        migrations.AddField(
            model_name='group',
            name='education_stage',
            field=models.CharField(blank=True, choices=[('primary', 'ابتدائي'), ('preparatory', 'إعدادي'), ('secondary', 'ثانوي')], max_length=20, verbose_name='المرحلة الدراسية'),
        ),
        migrations.AddField(
            model_name='group',
            name='education_year',
            field=models.CharField(blank=True, choices=[('1', 'أولى'), ('2', 'ثانية'), ('3', 'ثالثة')], max_length=5, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='group',
            name='gender_type',
            field=models.CharField(choices=[('male', 'بنين فقط'), ('female', 'بنات فقط'), ('mixed', 'مختلط')], default='mixed', max_length=10, verbose_name='نوع المجموعة (الجنس)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, help_text='ضرورية لطباعة ظهر كارنيه الطالب', null=True, upload_to='teachers/photos/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule_time',
            field=models.TimeField(verbose_name='وقت بداية الحصة'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, help_text='حقل اختياري', max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='التخصص (قديم)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='teachers.subject', verbose_name='التخصصات / المواد'),
        ),
    ]
