# Generated by Django 5.2.10 on 2026-02-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_add_room_scheduling_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["schedule_day", "schedule_time"],
                "verbose_name": "مجموعة",
                "verbose_name_plural": "المجموعات",
            },
        ),
        migrations.RenameIndex(
            model_name="group",
            new_name="groups_room_id_18638f_idx",
            old_name="group_room_schedule_idx",
        ),
        migrations.RenameIndex(
            model_name="group",
            new_name="groups_schedul_9b31a4_idx",
            old_name="group_day_time_idx",
        ),
        migrations.RenameIndex(
            model_name="group",
            new_name="groups_is_acti_c63b73_idx",
            old_name="group_is_active_idx",
        ),
        migrations.AlterField(
            model_name="group",
            name="schedule_time",
            field=models.TimeField(verbose_name="وقت بدء الحصة"),
        ),
    ]
