# Generated by Django 5.2.10 on 2026-02-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_subject_remove_group_unique_room_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='education_year',
            field=models.CharField(blank=True, choices=[('1', 'الصف الأول'), ('2', 'الصف الثاني'), ('3', 'الصف الثالث'), ('4', 'الصف الرابع'), ('5', 'الصف الخامس'), ('6', 'الصف السادس')], max_length=5, verbose_name='السنة الدراسية'),
        ),
    ]
