# Generated by Django 4.2.27 on 2026-02-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qr_code_base64',
            field=models.TextField(blank=True, help_text='رمز QR للمدرس لتسجيل حضور الحصص', null=True, verbose_name='رمز الاستجابة السريعة (QR)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qr_code_generated_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ آخر توليد لرمز QR', null=True, verbose_name='تاريخ توليد QR'),
        ),
    ]
