# Generated by Django 5.0.1 on 2026-03-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0004_add_soft_delete_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="sessions_per_month",
            field=models.PositiveIntegerField(
                default=4, verbose_name="عدد الحصص في الشهر"
            ),
        ),
    ]
