# Generated by Django 5.0.1 on 2026-03-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0005_group_sessions_per_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="education_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "ابتدائي"),
                    ("preparatory", "إعدادي"),
                    ("secondary", "ثانوي"),
                ],
                max_length=20,
                verbose_name="المرحلة الدراسية",
            ),
        ),
    ]
