# Generated by Django 5.0.1 on 2026-04-08 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0006_subject_education_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSchedule",
            fields=[
                ("schedule_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Saturday", "السبت"),
                            ("Sunday", "الأحد"),
                            ("Monday", "الاثنين"),
                            ("Tuesday", "الثلاثاء"),
                            ("Wednesday", "الأربعاء"),
                            ("Thursday", "الخميس"),
                            ("Friday", "الجمعة"),
                        ],
                        max_length=10,
                        verbose_name="يوم الحصة",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="وقت بداية الحصة")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="مدة الحصة بالدقائق",
                        verbose_name="مدة الحصة (بالدقائق)",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="teachers.group",
                        verbose_name="المجموعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول مجموعة",
                "verbose_name_plural": "جداول المجموعات",
                "db_table": "group_schedules",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("group", "day_of_week")},
            },
        ),
    ]
