# Generated by Django 5.0.1 on 2026-04-08 11:08

from django.db import migrations


def migrate_group_schedules(apps, schema_editor):
    """Copy existing Group schedule_day/schedule_time into GroupSchedule records"""
    Group = apps.get_model('teachers', 'Group')
    GroupSchedule = apps.get_model('teachers', 'GroupSchedule')

    for group in Group.objects.all():
        if group.schedule_day and group.schedule_time:
            GroupSchedule.objects.get_or_create(
                group=group,
                day_of_week=group.schedule_day,
                defaults={
                    'start_time': group.schedule_time,
                    'duration': group.duration_minutes,
                }
            )


def reverse_migrate(apps, schema_editor):
    """Reverse: nothing to do, old fields still exist"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0007_add_group_schedule_model"),
    ]

    operations = [
        migrations.RunPython(migrate_group_schedules, reverse_migrate),
    ]
