# Generated by Django 5.0.1 on 2026-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0008_migrate_group_to_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="education_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "ابتدائي"),
                    ("preparatory", "إعدادي"),
                    ("secondary", "ثانوي"),
                ],
                default="",
                max_length=20,
                verbose_name="المرحلة الدراسية",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم المادة"),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("name", "education_stage")},
        ),
    ]
