# Generated by Django 5.0.1 on 2026-08-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_remove_group_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCycle',
            fields=[
                ('cycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField(help_text='ترقيم تسلسلي لكل مجموعة (1، 2، 3، ...)', verbose_name='رقم الدورة')),
                ('sessions_planned', models.PositiveIntegerField(help_text='نسخة من sessions_per_month وقت فتح الدورة', verbose_name='عدد الحصص المخطط لها')),
                ('started_on', models.DateField(blank=True, help_text='تاريخ أول حصة في الدورة — فارغ يعني دورة محجوزة لم تبدأ بعد', null=True, verbose_name='تاريخ بداية الدورة')),
                ('closed_on', models.DateField(blank=True, help_text='تاريخ آخر حصة مُحتسَبة — فارغ يعني الدورة مفتوحة حاليًا', null=True, verbose_name='تاريخ إغلاق الدورة')),
                ('is_legacy', models.BooleanField(default=False, help_text='أُنشئت بأثر رجعي من بيانات الاشتراك الزمني القديم', verbose_name='دورة قديمة مُرحَّلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='teachers.group', verbose_name='المجموعة')),
            ],
            options={
                'verbose_name': 'دورة مجموعة',
                'verbose_name_plural': 'دورات المجموعات',
                'db_table': 'group_cycles',
                'ordering': ['group_id', 'index'],
            },
        ),
        migrations.AddConstraint(
            model_name='groupcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_on__isnull', True), ('started_on__isnull', False)), fields=('group',), name='one_open_cycle_per_group'),
        ),
        migrations.AlterUniqueTogether(
            name='groupcycle',
            unique_together={('group', 'index')},
        ),
    ]
