# Generated by Django 5.0.1 on 2026-08-30 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_cycle_billing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='sessions_per_month',
            field=models.PositiveIntegerField(default=4, help_text='طول الدورة المحاسبية بالحصص — 8 حصص كحد أقصى. 0 يعني أن المجموعة غير مفوترة بالدورات.', validators=[django.core.validators.MaxValueValidator(8)], verbose_name='عدد الحصص في الشهر'),
        ),
    ]
