# Generated by Django 5.0.1 on 2026-08-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_alter_group_sessions_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='education_stage',
            field=models.CharField(blank=True, choices=[('primary', 'ابتدائي'), ('preparatory', 'إعدادي'), ('secondary', 'ثانوي'), ('foundation', 'تأسيس'), ('courses', 'كورسات')], max_length=20, verbose_name='المرحلة الدراسية'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='education_stage',
            field=models.CharField(blank=True, choices=[('primary', 'ابتدائي'), ('preparatory', 'إعدادي'), ('secondary', 'ثانوي'), ('foundation', 'تأسيس'), ('courses', 'كورسات')], default='', max_length=20, verbose_name='المرحلة الدراسية'),
        ),
    ]
