# Generated by Django 5.0.1 on 2026-09-26 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_alter_group_education_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='sessions_per_month',
            field=models.PositiveIntegerField(default=8, help_text='طول الدورة المحاسبية بالحصص — 8 حصص كحد أقصى. 0 يعني أن المجموعة غير مفوترة بالدورات.', validators=[django.core.validators.MaxValueValidator(8)], verbose_name='عدد الحصص في الشهر'),
        ),
    ]
