# Generated by Django 5.0.1 on 2026-10-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_group_default_eight_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcycle',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='ملاحظات المجموعة على الدورة دي — بتتكتب من كشف الدورة', verbose_name='ملاحظات الدورة'),
        ),
    ]
