# Generated by Django 5.2.10 on 2026-01-27 06:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(max_length=255, verbose_name="اسم الطالب"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="رقم الهاتف"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("attendance", "حضور"),
                            ("late", "تأخير"),
                            ("absent", "غياب"),
                            ("payment_reminder", "تذكير بالدفع"),
                            ("payment_warning", "تحذير قبل الحظر"),
                            ("block_late", "منع - تأخير"),
                            ("block_payment", "منع - مصروفات"),
                            ("custom", "مخصص"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                ("message", models.TextField(verbose_name="نص الرسالة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "تم الإرسال"),
                            ("failed", "فشل"),
                            ("pending", "قيد الانتظار"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="وقت الإرسال"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل إشعار",
                "verbose_name_plural": "سجل الإشعارات",
                "db_table": "notification_logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
