# Generated by Django 4.2.27 on 2026-02-07 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_student_education_stage_student_education_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0002_subject_remove_group_unique_room_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('message_text', models.TextField(verbose_name='نص الرسالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب واتساب',
                'verbose_name_plural': 'قوالب واتساب',
                'db_table': 'whatsapp_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('message_text', models.TextField(verbose_name='نص الرسالة')),
                ('message_type', models.CharField(choices=[('student', 'رسالة للطالب'), ('parent', 'رسالة لولي الأمر'), ('group', 'رسالة جماعية'), ('attendance', 'تقرير الحضور'), ('payment', 'تقرير المدفوعات'), ('custom', 'رسالة مخصصة')], default='custom', max_length=20, verbose_name='نوع الرسالة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال'), ('delivered', 'تم التسليم')], default='pending', max_length=20, verbose_name='حالة الرسالة')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='teachers.group', verbose_name='المجموعة')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='المُرسِل')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'رسالة واتساب',
                'verbose_name_plural': 'رسائل واتساب',
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='whatsapp_me_status_9b76f6_idx'), models.Index(fields=['phone_number', '-created_at'], name='whatsapp_me_phone_n_5f957d_idx'), models.Index(fields=['message_type', '-created_at'], name='whatsapp_me_message_c4d5c0_idx')],
            },
        ),
    ]
