# Generated by Django 5.2.10 on 2026-01-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_add_template_and_preferences"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "سجل إشعار",
                "verbose_name_plural": "سجل الإشعارات",
            },
        ),
        migrations.RemoveIndex(
            model_name="notificationcost",
            name="cost_month_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="notificatio_status_e36129_idx",
            old_name="notif_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="notificatio_notific_250714_idx",
            old_name="notif_type_status_idx",
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AlterUniqueTogether(
            name="notificationcost",
            unique_together={("month",)},
        ),
    ]
